version: '3.8'

services:

  service-a:
    build: ./service-a
    container_name: python-service
    volumes:
      - ./service-a/data:/app/data   
    depends_on:
      - service-b

  service-b:
    build: ./service-b
    container_name: spring-service
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: studentdb
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5